//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace AssemblyCSharp
{
    public class Attaque
    {
        public double degat { get; set; }
        public double redu_armure { get; set; }
        public String Type { get; set; }
        public int nb_attaque { get; set; }
        public int portee { get; set; }
        public int zone { get; set; }
        public Attaque(double degat, double redu_armure, int portee, int zone, string type, int nb_attaque)
        {
            this.degat = degat;
            this.redu_armure = redu_armure;
            this.portee = portee;
            this.zone = zone;
            this.Type = type;
            this.nb_attaque = nb_attaque;
        }
    }

}

