//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp
{
    public class Case : MonoBehaviour
    {
        public Boolean occupe { get; set; }
        public GameObject element { get; set; }
        // Ceci est une portion de code OLILOL
        //private SpriteRenderer spr;


        // Use this for initialization
        void Start()
        {
            // Ceci est une portion de code OLILOL
            //spr = GetComponent<SpriteRenderer>();

        }

        // Update is called once per frame
        void Update()
        {
            // Ceci est une portion de code OLILOL
            /*int alea = UnityEngine.Random.Range(1,5);
            switch (alea)
            {
                case 1 :
                    spr.color = Color.blue;
                    break;
                case 2 :
                    spr.color = Color.red;
                    break;
                case 3 :
                    spr.color = Color.magenta;
                    break;
                case 4 :
                    spr.color = Color.yellow;
                    break;
                case 5 :
                    spr.color = Color.cyan;
                    break;
            }*/
        }
    }
}

