//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
namespace AssemblyCSharp
{
    public class Unite : Element
    {
        public static int stockage = 50;
        public GameObject produit { get; set; }
        private Special[] capacites { get; set; }
        public int mouvement { get; set; }
        public List<char> deplacement { get; set; }
        public Attaque attaque { get; set; }
        public Dictionary<float, Vector3> enn_pos { get; set; }
        public void addSpecial(Special capacite)
        {
            int i = 0;
            while (i < this.capacites.Length)
            {
                if (capacites[i] == null && i < 3)
                {
                    capacites[i] = capacite;
                }

            }
        }

        protected override void Start()
        {
            deplacement = new List<char>();
        }

        // Update is called once per frame
        protected override void Update()
        {
            base.Update();

        }
    }
}

